lib/omsmailer_web/controllers/page_controller.ex, test/omsmailer_web/controllers/page_controller_test.exs
I wrongly matched the output of render_template, as it returns a tuple and not just the html
=> Patch page controller to work with multiple bodies

lib/omsmailer/page.ex, lib/omsmailer_web/controllers/page_controller.ex, mix.exs, test/omsmailer_web/controllers/page_controller_test.exs
Implemented custom headers for cc, bcc and reply_to
=> Additional headers

lib/omsmailer_web/templates/page/statutory_applied.html.eex, lib/omsmailer_web/templates/page/statutory_edited.html.eex, test/omsmailer_web/controllers/page_controller_test.exs
@blacksph3re can you check if it's okay? not sure about eex syntax
=> Statutory templates for applying and editing application

lib/omsmailer_web/templates/page/statutory_applied.html.eex, lib/omsmailer_web/templates/page/statutory_edited.html.eex, test/omsmailer_web/controllers/page_controller_test.exs
should work okay this time, lol
=> Fix statutory templates

lib/omsmailer_web/templates/page/statutory_applied.html.eex, lib/omsmailer_web/templates/page/statutory_edited.html.eex, test/omsmailer_web/controllers/page_controller_test.exs
Sorry @blacksph3re but I managed to mess up again, this should fix this. Added more tests to really test stuff.
=> Fix statutory applications (really)

lib/omsmailer_web/templates/page/statutory_applied.html.eex, lib/omsmailer_web/templates/page/statutory_edited.html.eex
Before that question displaying had a mistake with index offset, this should fix it. I've hotfixed it on prod for now, to re-deploy when this would be deployed.
=> Fixed question indexes for statutory templates

lib/omsmailer_web/templates/page/member_joined.html.eex
Should fix that ugly button. (not tested though)
=> Fixed mail template for join request

.travis.yml, docker/.env, docker/docker-compose-secrets.yml, docker/docker-compose.dev.yml, docker/docker-compose.yml, docker/mail_transfer_agent/Dockerfile, docker/oms-mailer/Dockerfile
=> impr(docker): manifest is now perfect

docker/docker-compose.yml, docker/oms-mailer/Dockerfile, lib/omsmailer_web/controllers/page_controller.ex, lib/omsmailer_web/router.ex, test/omsmailer_web/controllers/page_controller_test.exs
1. Added the /healthcheck endpoint
2. Added tests for it
3. Added docker healthcheck using it
4. Expose it (and only it) through traefik
=> Added /healthcheck

.gitignore, .npmrc, CHANGELOG.md, commitlint.config.js, docker/oms-mailer/Dockerfile, lib/omsmailer_web/controllers/page_controller.ex, lib/omsmailer_web/router.ex, package-lock.json, package.json
Fixes MEMB-555, same as core basically
=> Add conventional commits

CHANGELOG.md, lib/omsmailer_web/plugs/request_logger_plug.ex, lib/omsmailer_web/router.ex, package-lock.json, package.json
Fixes MEMB-692.
Basically the copypaste of core's plug without user displaying and stuff.
=> Add request logging

.circleci/config.yml, CHANGELOG.md, package-lock.json, package.json
Fixes MEMB-678, same as on core (literally copied the file from core and `s/core-elixir/mailer` lol)
=> Switched to CircleCI from Travis. 

.circleci/config.yml, CHANGELOG.md, docker/docker-compose.dev.yml, docker/docker-compose.yml, package-lock.json, package.json
Fixing stuff that wasn't fixed on mailer for production env.
=> Build mailing agent image

.circleci/config.yml, CHANGELOG.md, docker/docker-compose.dev.yml, docker/mail_transfer_agent/Dockerfile, package-lock.json, package.json
fixes my previous agent building, should work now
=> Fixed mail-transfer-agent building

.circleci/config.yml, .travis.yml, CHANGELOG.md, config/config.exs, docker/docker-compose-secrets.yml, docker/docker-compose.yml, docker/dummy_secret, docker/mail_transfer_agent/run.sh, docker/oms-mailer/Dockerfile, package-lock.json, package.json
Fixes MEMB-676, required for moving to @aegee.eu mailing.
Changes:
1) removed secrets, moved everything to .env file
2) that's pretty much it :D
=> Refactor env settings

CHANGELOG.md, lib/omsmailer_web/templates/page/statutory_applied.html.eex, lib/omsmailer_web/templates/page/statutory_board_applied.html.eex, lib/omsmailer_web/templates/page/statutory_board_edited.html.eex, lib/omsmailer_web/templates/snippets/application_info.html.eex, package-lock.json, package.json, test/omsmailer_web/controllers/page_controller_test.exs
=> Add statutory board applied template

lib/omsmailer_web/templates/page/confirm_email.html.eex, lib/omsmailer_web/templates/page/events_applied.html.eex, lib/omsmailer_web/templates/page/events_edited.html.eex, lib/omsmailer_web/templates/page/membership_expired.html.eex, lib/omsmailer_web/templates/page/statutory_applied.html.eex, lib/omsmailer_web/templates/page/statutory_edited.html.eex, lib/omsmailer_web/templates/page/welcome.html.eex, test.html
I just noticed in my email a weird alt text at the start
=> fix(templates): Update alt text

test/omsmailer_web/controllers/page_controller_test.exs
apparently a few of them are broken
=> chore: fix tests

package-lock.json, package.json
semantic-release had to be updated because of the marked vulnerability, so I went ahead and updated the rest as well. Only husky is a major version change
=> chore(deps): update js deps

lib/omsmailer_web/templates/page/statutory_applied.html.eex
Tests are still broken as always
=> fix(statutory): add mailing lists link to application email. Fixes HELP-1639

lib/omsmailer_web/templates/page/new_member.html.eex
Draft until approved by CD/HRC
Core PR is https://github.com/AEGEE/core/pull/278
=> feat(new_member): add new member email

lib/omsmailer_web/templates/page/statutory_board_applied.html.eex, lib/omsmailer_web/templates/page/summeruniversity_application_status_updated.html.eex, lib/omsmailer_web/templates/page/summeruniversity_board_applied.html.eex, lib/omsmailer_web/templates/page/summeruniversity_board_edited.html.eex, lib/omsmailer_web/templates/page/summeruniversity_organizer_applied.html.eex, lib/omsmailer_web/templates/page/summeruniversity_organizer_edited.html.eex
Like always, test does not pass. Not an issue with this PR
=> fix(su): add board/organizer application emails
